### ISSUE TITLE
Кто-то не умеет пользоваться компьютером...

### ISSUE THREAD

**Issue by zaruda** [Khmelov/PISL2017-01-26#36]
Было бы неплохо удалить лишнее
http://joxi.ru/ZrJGGy4hj0ypmj

**Comment by zaruda** [comment]
чтобы не мешала. не каждый в презентации посмотрит решение проблемы

**Comment by taleh007** [comment]
@zaruda Просто "Mark Directory as... Excluded"

**Comment by zaruda** [comment]
@taleh007 I know, но это же лишний мусор)

**Comment by Shpilevskiy** [comment]
В README **большими** буквами написано, что нужно сделать - 
![2017-03-17 14-38-56](https://cloud.githubusercontent.com/assets/11997804/24041667/33147506-0b17-11e7-9c28-9ec1d1107622.png)

И не просто так стоит просьба не исправлять чужие папки. Сомневаюсь, что у кого-то могут возникнуть проблемы с чтением.
